# -*- coding: utf-8 -*-
"""function1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cSJMN_Qfs7LslyEu5Omi8eqbOU9C3VyH
"""

def most_frequent(string):

  d = dict()

  for key in string:

    if key not in d:

      d[key] = 1

    else:

      d[key] += 1

  return d

word=input("enter word to check : ")

print(most_frequent(word))